[HardwareConfig]
# GPIO PIN CONFIGURATION
#lox venting valve
Solenoid_LOX_VENT = 21
Solenoid_KERO_VENT = 26

#combustion chamber entry valve
Solenoid_LOX_ENTRY = 23
Solenoid_KERO_ENTRY = 16

# tank pressing valve
Solenoid_HE_ENTRY = 19

#ignition pin
SIGNAL_IGNITION = 13

[2WAY]
LOXVENT = 12
KEROVENT = 27
KEROMAIN = 5
LOXMAIN = 8
PRESS = 25


[DataConfig]

# venting data publisher nodes
PRESSURE_DATAFEED_PORT = 1001
PRESSURE_ERROR_DATAFEED_PORT = 1005

# Load Cell Data Publisher node

LOAD_CELL_DATAFEED_PORT = 1002

#Command and Control Nodes and System Reporting
CMD_PROMPT_PORT = 1003

SYSTEM_STATE_PORT = 1004

[NetworkConfig]
# over tcp
# set RPI3 networking to a static IPV4 Port and then connect to it on this
# i.e. 10.0.69.1 is the command station and 10.0.69.34 is the RPI3
# TCP over 0MQ (ZeroMQ)
HARDWARE_NETWORK_TARGET = "10.72.0.122"



[PressureConfig]
# constants to abide by dude

LOX_MAX_PSI = 600
KERO_MAX_PSI = 750

[PressureADCConfig]
# example values
LOX_PSI1 = [6,7]

[MA]
# m, b format
MA_FILTER_LEN = 20

[PressureCalibration]
LOX_PSI1 = [-943, 0,1873, 100, 3]
#KERO_PSI2 =

# pid controller gains
[LOXPIDGains]
p = 1.5
i = 0
d = 0

[KEROPIDGains]
p = 1.5
i = 0
d = 0

