[HardwareConfig]
# GPIO PIN CONFIGURATION
#lox venting valve
Solenoid_LOX_VENT = 21
Solenoid_KERO_VENT = 8

#combustion chamber entry valve
Solenoid_LOX_ENTRY = 7
Solenoid_KERO_ENTRY = 3

# tank pressing valve
Solenoid_HE_ENTRY = 12

#ignition pin
SIGNAL_IGNITION = 26

[DataConfig]

# venting data publisher nodes
PRESSURE_DATAFEED_PORT = 1001

# Load Cell Data Publisher node

LOAD_CELL_DATAFEED_PORT = 1002

#Command and Control Nodes and System Reporting
CMD_PROMPT_PORT = 1003

SYSTEM_STATE_PORT = 1004

[NetworkConfig]
# over tcp
# set RPI3 networking to a static IPV4 Port and then connect to it on this
# i.e. 10.0.69.1 is the command station and 10.0.69.34 is the RPI3
# TCP over 0MQ (ZeroMQ)
HARDWARE_NETWORK_TARGET = "10.72.0.122"



[PressureConfig]
# constants to abide by dude

LOX_MAX_PSI = 600
KERO_MAX_PSI = 750

[PressureADCConfig]
# example values
LOX_SENSOR1 = [6,7]
KERO_SENSOR2 = [8,9]
HE_SENSOR3 = [12,11]

[PressureCalibration]
# m, b format

SENSOR1_CALI = []
SENSOR2_CALI = []
SENSOR3_CALI = []


# pid controller gains
[LOXPIDGains]
p = 0.3
i = 3
d = 0.4

[KEROPIDGains]
p = 0.4
i = 3
d = 0.2

